// <auto-generated />
namespace Kollaborator.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class chat1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chat1));
        
        string IMigrationMetadata.Id
        {
            get { return "201412171838281_chat1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
